INSERT INTO university (korean_name, english_name, campus, email_domain)
VALUES
    ('국립금오공과대학교', 'Kumoh National Institute Of Technology', 'MAIN', 'kumoh.ac.kr'),
    ('국립목포대학교', 'Mokpo National University', 'MAIN', 'mokpo.ac.kr'),
    ('국립목포해양대학교', 'Mokpo National Maritime University', 'MAIN', 'mmu.ac.kr'),
    ('국립부경대학교', 'Pukyong National University', 'MAIN', 'pknu.ac.kr'),
    ('국립순천대학교', 'Sunchon National University', 'MAIN', 'scnu.ac.kr'),
    ('국립창원대학교', 'Changwon National University', 'MAIN', 'changwon.ac.kr'),
    ('국립한국교통대학교', 'Korea National University Of Transportation', 'MAIN', 'ut.ac.kr'),
    ('국립한국해양대학교', 'Korea Maritime & Ocean University', 'MAIN', 'kmou.ac.kr'),
    ('국립한밭대학교', 'Hanbat National University', 'MAIN', 'hanbat.ac.kr'),
    ('국민대학교', 'Kookmin University', 'MAIN', 'kookmin.ac.kr'),
    ('국제사이버대학교', 'Gukje Cyber University', 'MAIN', 'gjcu.ac.kr'),
    ('극동대학교', 'Far East University', 'MAIN', 'kdu.ac.kr'),
    ('글로벌사이버대학교', 'Global Cyber University', 'MAIN', 'global.ac.kr'),
    ('금강대학교', 'Geumgang University', 'MAIN', 'ggu.ac.kr'),
    ('김천대학교', 'Gimcheon University', 'MAIN', 'gimcheon.ac.kr'),
    ('나사렛대학교', 'Korea Nazarene University', 'MAIN', 'kornu.ac.kr'),
    ('남부대학교', 'Nambu University', 'MAIN', 'nambu.ac.kr'),
    ('남서울대학교', 'Namseoul University', 'MAIN', 'nsu.ac.kr'),
    ('남서울대학교(산업대)', 'Namseoul University', 'MAIN', 'nsu.ac.kr'),
    ('단국대학교', 'Dankook University', 'MAIN', 'dankook.ac.kr'),
    ('단국대학교', 'Dankook University', 'SECOND', 'dankook.ac.kr'),
    ('대구가톨릭대학교', 'Daegu Catholic University', 'MAIN', 'cu.ac.kr'),
    ('대구경북과학기술원', 'DGIST', 'MAIN', 'dgist.ac.kr'),
    ('대구교육대학교', 'Daegu National University Of Education', 'MAIN', 'dnue.ac.kr'),
    ('대구대학교', 'Daegu University', 'MAIN', 'daegu.ac.kr'),
    ('대구사이버대학교', 'Daegu Cyber University', 'MAIN', 'dcu.ac.kr'),
    ('대구예술대학교', 'Daegu Arts University', 'MAIN', 'dgau.ac.kr'),
    ('대구외국어대학교', 'Daegu University Of Foreign Studies', 'MAIN', 'dufs.ac.kr'),
    ('대구한의대학교', 'Daegu Haany University', 'MAIN', 'dhu.ac.kr'),
    ('대신대학교', 'Daeshin University', 'MAIN', 'daeshin.ac.kr'),
    ('대전가톨릭대학교', 'Daejeoncatholicuniversity', 'MAIN', 'dcatholic.ac.kr'),
    ('대전대학교', 'Daejeon University', 'MAIN', 'dju.ac.kr'),
    ('대전신학대학교', 'Daejeon Theological University', 'MAIN', 'daejeon.ac.kr'),
    ('대진대학교', 'Daejin University', 'MAIN', 'daejin.ac.kr'),
    ('덕성여자대학교', 'Duksung Women’S University', 'MAIN', 'duksung.ac.kr'),
    ('동국대학교', 'Dongguk University', 'MAIN', 'dongguk.edu'),
    ('동국대학교(WISE)', 'Dongguk University', 'BRANCH', 'wise.dongguk.ac.kr'),
    ('동덕여자대학교', 'Dongduk Women’s University', 'MAIN', 'dongduk.ac.kr'),
    ('동명대학교', 'Tongmyong University', 'MAIN', 'tu.ac.kr'),
    ('동서대학교', 'Dongseo University', 'MAIN', 'dongseo.ac.kr'),
    ('동신대학교', 'Dongshinuniversity', 'MAIN', 'dsu.ac.kr'),
    ('동아대학교', 'Dong-A University', 'MAIN', 'donga.ac.kr'),
    ('동양대학교', 'Dongyang University', 'MAIN', 'dyu.ac.kr'),
    ('동의대학교', 'Dong-Eui University', 'MAIN', 'deu.ac.kr'),
    ('디지털서울문화예술대학교', 'Digital Seoul Culture Arts University', 'MAIN', 'scau.ac.kr'),
    ('루터대학교', 'Luther University', 'MAIN', 'ltu.ac.kr'),
    ('명지대학교', 'Myongji University Natural Science Campus', 'MAIN', 'mju.ac.kr'),
    ('명지대학교', 'Myongji University Social Science Campus', 'SECOND', 'mju.ac.kr'),
    ('목원대학교', 'Mokwon University', 'MAIN', 'mokwon.ac.kr'),
    ('목포가톨릭대학교', 'Mokpo Catholic University', 'MAIN', 'mcu.ac.kr'),
    ('배재대학교', 'Pai Chai University', 'MAIN', 'pcu.ac.kr'),
    ('백석대학교', 'Baekseok University', 'MAIN', 'bu.ac.kr'),
    ('부산가톨릭대학교', 'Catholic University Of Pusan', 'MAIN', 'cup.ac.kr'),
    ('부산교육대학교', 'Busan National University Of Education', 'MAIN', 'bnue.ac.kr'),
    ('부산대학교', 'Pusan National University', 'MAIN', 'pusan.ac.kr'),
    ('부산디지털대학교', 'Busandigital University', 'MAIN', 'bdu.ac.kr'),
    ('부산외국어대학교', 'Busan University Of Foreign Studies', 'MAIN', 'bufs.ac.kr'),
    ('부산장신대학교', 'Busan Presbyterian University', 'MAIN', 'bpu.ac.kr'),
    ('사이버한국외국어대학교', 'Cyber Hankuk University Of Foreign Studies', 'MAIN', 'cufs.ac.kr'),
    ('삼육대학교', 'Sahmyook University', 'MAIN', 'syu.ac.kr'),
    ('상명대학교', 'Sangmyung University (Seoul)', 'MAIN', 'smu.ac.kr'),
    ('상명대학교', 'Sangmyung University', 'SECOND', 'smuc.ac.kr'),
    ('상지대학교', 'Sangji University', 'MAIN', 'sangji.ac.kr'),
    ('서강대학교', 'Sogang University', 'MAIN', 'sogang.ac.kr'),
    ('서경대학교', 'Seokyeong University', 'MAIN', 'skuniv.ac.kr'),
    ('서남대학교', 'Seonam University', 'MAIN', 'seonam.ac.kr'),
    ('서남대학교', 'Seonam University', 'SECOND', 'asan.seonam.ac.kr'),
    ('서울과학기술대학교', 'Seoul National University Of Science And Technology', 'MAIN', 'seoultech.ac.kr'),
    ('서울교육대학교', 'Seoul National University Of Education', 'MAIN', 'snue.ac.kr'),
    ('서울기독대학교', 'Seoul Christian University', 'MAIN', 'scu.ac.kr'),
    ('서울대학교', 'Seoul National University', 'MAIN', 'snu.ac.kr'),
    ('서울디지털대학교', 'Seoul Digital University', 'MAIN', 'sdu.ac.kr'),
    ('서울사이버대학교', 'Seoul Cyber University', 'MAIN', 'iscu.ac.kr'),
    ('서울시립대학교', 'University Of Seoul', 'MAIN', 'uos.ac.kr'),
    ('서울신학대학교', 'Seoul Theological University', 'MAIN', 'stu.ac.kr'),
    ('서울여자대학교', 'Seoul Women’s University', 'MAIN', 'swu.ac.kr'),
    ('서울장신대학교', 'Seoul Jangsin University', 'MAIN', 'sjs.ac.kr'),
    ('서울한영대학교', 'Seoul Hanyoung University', 'MAIN', 'shyu.ac.kr'),
    ('서원대학교', 'Seowon University', 'MAIN', 'seowon.ac.kr'),
    ('선문대학교', 'Sun Moon University', 'MAIN', 'sunmoon.ac.kr'),
    ('성결대학교', 'Sungkyul University', 'MAIN', 'sungkyul.ac.kr'),
    ('성공회대학교', 'Sungkonghoe University', 'MAIN', 'skhu.ac.kr'),
    ('성균관대학교', 'Sungkyunkwan University', 'MAIN', 'skku.edu'),
    ('성신여자대학교', 'Sungshin Women’S University', 'MAIN', 'sungshin.ac.kr'),
    ('세명대학교', 'Semyung University', 'MAIN', 'semyung.ac.kr'),
    ('세종대학교', 'Sejong University', 'MAIN', 'sejong.ac.kr'),
    ('세종사이버대학교', 'Sejong Cyber University', 'MAIN', 'sjcu.ac.kr'),
    ('세한대학교', 'Sehan University', 'MAIN', 'sehan.ac.kr'),
    ('송원대학교', 'Songwon University', 'MAIN', 'songwon.ac.kr'),
    ('수원가톨릭대학교', 'Suwon Catholic University', 'MAIN', 'suwoncatholic.ac.kr'),
    ('수원대학교', 'The University Of Suwon', 'MAIN', 'suwon.ac.kr'),
    ('숙명여자대학교', 'Sookmyung Women’S University', 'MAIN', 'sookmyung.ac.kr'),
    ('순복음총회신학교', 'Korea Christian College', 'MAIN', 'kcc.ac.kr'),
    ('순천향대학교', 'Soonchunhyang University', 'MAIN', 'sch.ac.kr'),
    ('숭실대학교', 'Soongsil University', 'MAIN', 'ssu.ac.kr'),
    ('숭실사이버대학교', 'Korea Soongsil Cyber University', 'MAIN', 'kcu.ac'),
    ('신경주대학교', 'SinGyeongju University', 'MAIN', 'gju.ac.kr'),
    ('신라대학교', 'Silla University', 'MAIN', 'silla.ac.kr'),
    ('신한대학교', 'Shinhan Unvirsity', 'MAIN', 'shinhan.ac.kr'),
    ('신한대학교', 'Shinhan University', 'SECOND', 'shinhan.ac.kr'),
    ('아신대학교', 'ACTS University', 'MAIN', 'acts.ac.kr'),
    ('아주대학교', 'Ajou University', 'MAIN', 'ajou.ac.kr'),
    ('안양대학교', 'Anyang University', 'MAIN', 'anyang.ac.kr'),
    ('안양대학교', 'Anyang University', 'SECOND', 'anyang.ac.kr'),
    ('연세대학교', 'Yonsei University', 'MAIN', 'yonsei.ac.kr'),
    ('연세대학교(미래)', 'Yonsei University MIRAE Campus', 'BRANCH', 'yonsei.ac.kr'),
    ('영남대학교', 'Yeungnam University', 'MAIN', 'yu.ac.kr'),
    ('영남신학대학교', 'Youngnam Theological University & Seminary', 'MAIN', 'ytus.ac.kr'),
    ('영산대학교(양산)', 'Youngsan University', 'SECOND', 'ysu.ac.kr'),
    ('영산대학교(해운대)', 'Youngsan University', 'MAIN', 'ysu.ac.kr'),
    ('영산선학대학교', 'Youngsan University Of Seon Studies', 'MAIN', 'youngsan.ac.kr'),
    ('예수대학교', 'Jesus University', 'MAIN', 'jesus.ac.kr'),
    ('예원예술대학교', 'Yewon Arts University', 'MAIN', 'yewon.ac.kr'),
    ('예원예술대학교', 'Yewon Arts University', 'SECOND', 'yewon.ac.kr'),
    ('용인대학교', 'Yong In University', 'MAIN', 'yongin.ac.kr'),
    ('우석대학교', 'Woosuk University', 'MAIN', 'woosuk.ac.kr'),
    ('우송대학교', 'Woosong University', 'MAIN', 'wsu.ac.kr'),
    ('우송대학교(산업대)', 'Woosong University', 'MAIN', 'wsu.ac.kr'),
    ('울산과학기술원', 'Ulsan National Institute of Science and Technology', 'MAIN', 'unist.ac.kr'),
    ('울산대학교', 'University Of Ulsan', 'MAIN', 'ulsan.ac.kr'),
    ('원광대학교', 'Wonkwang University', 'MAIN', 'wku.ac.kr'),
    ('원광디지털대학교', 'Wonkwang Digital University', 'MAIN', 'wdu.ac.kr'),
    ('위덕대학교', 'Uiduk University', 'MAIN', 'uu.ac.kr'),
    ('유원대학교', 'U1 University', 'MAIN', 'U1.ac.kr'),
    ('을지대학교', 'Eulji University', 'MAIN', 'eulji.ac.kr'),
    ('을지대학교', 'Eulji University', 'SECOND', 'eulji.ac.kr'),
    ('을지대학교', 'Eulji University', 'THIRD', 'eulji.ac.kr'),
    ('이화여자대학교', 'Ewha Womans University', 'MAIN', 'ewha.ac.kr'),
    ('인제대학교', 'Inje University', 'MAIN', 'inje.ac.kr'),
    ('인제대학교', 'Inje University', 'SECOND', 'inje.ac.kr'),
    ('인천가톨릭대학교', 'Incheon Catholic University', 'MAIN', 'iccu.ac.kr'),
    ('인천가톨릭대학교', 'Incheon Catholic University', 'SECOND', 'iccu.ac.kr'),
    ('인천대학교', 'Incheon National University', 'MAIN', 'inu.ac.kr'),
    ('인하대학교', 'Inha University', 'MAIN', 'inha.ac.kr'),
    ('장로회신학대학교', 'Presbyterian University & Theological Seminary', 'MAIN', 'puts.ac.kr'),
    ('전남대학교', 'Chonnam National University', 'MAIN', 'chonnam.ac.kr'),
    ('전남대학교', 'Chonnam National University', 'SECOND', 'chonnam.ac.kr'),
    ('전북대학교', 'Jeonbuk National University', 'MAIN', 'jbnu.ac.kr'),
    ('전주교육대학교', 'Jeonju National University Of Education', 'MAIN', 'jnue.kr'),
    ('전주대학교', 'Jeonju University', 'MAIN', 'jj.ac.kr'),
    ('정석대학', 'Jungseok Institute Of Technology', 'MAIN', ''),
    ('제주국제대학교', 'Jejuinternationaluniversity', 'MAIN', 'jeju.ac.kr'),
    ('제주대학교', 'Jeju National University', 'MAIN', 'jejunu.ac.kr'),
    ('조선대학교', 'Chosun University', 'MAIN', 'chosun.ac.kr'),
    ('중부대학교', 'Joongbu University', 'MAIN', 'joongbu.ac.kr'),
    ('중앙대학교', 'Chung-Ang University', 'MAIN', 'cau.ac.kr'),
    ('중앙대학교', 'Chung-Ang University', 'SECOND', 'cau.ac.kr'),
    ('중앙승가대학교', 'Joong-Ang Sangha University', 'MAIN', 'admission.sangha.ac.kr'),
    ('중원대학교', 'Jungwon University', 'MAIN', 'jwu.ac.kr'),
    ('진주교육대학교', 'Chinju National Uinversity Of Education', 'MAIN', 'cue.ac.kr'),
    ('진주산업대학교(산업대)', 'Jinju National University', 'MAIN', 'gntech.ac.kr'),
    ('차의과학대학교', 'CHA University', 'MAIN', 'cha.ac.kr'),
    ('창신대학교', 'Changshin University', 'MAIN', 'cs.ac.kr'),
    ('청운대학교', 'Chungwoon University', 'MAIN', 'chungwoon.ac.kr'),
    ('청주교육대학교', 'Chongjunationaluniversityofeducation', 'MAIN', 'cje.ac.kr'),
    ('청주대학교', 'Cheongju University', 'MAIN', 'cju.ac.kr'),
    ('초당대학교', 'Chodang University', 'MAIN', 'cdu.ac.kr'),
    ('총신대학교', 'Chongshin University', 'MAIN', 'chongshin.ac.kr'),
    ('추계예술대학교', 'Chugye University For The Arts', 'MAIN', 'chugye.ac.kr'),
    ('춘천교육대학교', 'Chuncheon National University Of Education', 'MAIN', 'cnue.ac.kr'),
    ('충남대학교', 'Chungnam National University', 'MAIN', 'cnu.ac.kr'),
    ('충북대학교', 'Chungbuk National University', 'MAIN', 'chungbuk.ac.kr'),
    ('칼빈대학교', 'Calvin University', 'MAIN', 'calvin.ac.kr'),
    ('탐라대학교', 'Tamna University', 'MAIN', 'tnu.ac.kr'),
    ('태재대학교', 'TAEJAE UNIVERSITY', 'MAIN', 'taejae.ac.kr'),
    ('평택대학교', 'Pyeongtaek University', 'MAIN', 'ptu.ac.kr'),
    ('포항공과대학교', 'Pohang University Of Science And Technology (Postech)', 'MAIN', 'postech.ac.kr'),
    ('한경국립대학교', 'Hankyong National University', 'MAIN', 'hknu.ac.kr'),
    ('한국공학대학교', 'Tech University of Korea', 'MAIN', 'tukorea.ac.kr'),
    ('한국과학기술원', 'Korea Advanced Institute of Science and Technology(KAIST)', 'MAIN', 'kaist.ac.kr'),
    ('한국교원대학교', 'Korea National University Of Education', 'MAIN', 'knue.ac.kr'),
    ('한국기술교육대학교', 'Korea University of Technology and Education', 'MAIN', 'koreatech.ac.kr'),
    ('한국방송통신대학교', 'Korea National Open University', 'MAIN', 'knou.ac.kr'),
    ('한국성서대학교', 'Korean Bible University', 'MAIN', 'bible.ac.kr'),
    ('한국에너지공과대학교', 'Korea institute of Energy Technology', 'MAIN', 'kentech.ac.kr'),
    ('한국열린사이버대학교', 'Open Cyber University Of Korea (OCU)', 'MAIN', 'ocu.ac.kr'),
    ('한국예술종합학교', 'Korea National University Of Arts', 'MAIN', 'Karts.ac.kr'),
    ('한국외국어대학교', 'Hankuk University Of Foreign Studies', 'MAIN', 'hufs.ac.kr'),
    ('한국전통문화대학교', 'Korea National University Of Cultural Heritage', 'MAIN', 'knuh.ac.kr'),
    ('한국체육대학교', 'Korea National Sport University', 'MAIN', 'knsu.ac.kr'),
    ('한국침례신학대학교', 'Korea Baptist Theological University/Seminary', 'MAIN', 'kbtus.ac.kr'),
    ('한국항공대학교', 'Korea Aerospace University', 'MAIN', 'kau.ac.kr'),
    ('한남대학교', 'Hannam University', 'MAIN', 'hannam.ac.kr'),
    ('한동대학교', 'Handong Global University', 'MAIN', 'handong.edu'),
    ('한라대학교', 'Halla University', 'MAIN', 'halla.ac.kr'),
    ('한려대학교', 'Hanlyo University', 'MAIN', 'hanlyo.ac.kr'),
    ('한림대학교', 'Hallym University', 'MAIN', 'hallym.ac.kr'),
    ('한밭대학교(산업대)', 'Hanbat National University', 'MAIN', 'hanbat.ac.kr'),
    ('한북대학교', 'Hanbuk University', 'MAIN', 'hanbuk.ac.kr'),
    ('한서대학교', 'Hanseo University', 'MAIN', 'hanseo.ac.kr'),
    ('한성대학교', 'Hansung University', 'MAIN', 'hansung.ac.kr'),
    ('한세대학교', 'Hansei University', 'MAIN', 'hansei.ac.kr'),
    ('한신대학교', 'Hanshin University', 'MAIN', 'hs.ac.kr'),
    ('한양대학교', 'Hanyang University', 'MAIN', 'hanyang.ac.kr'),
    ('한양대학교(ERICA)', 'Hanyang University Erica Campus', 'BRANCH', 'hanyang.ac.kr'),
    ('한양사이버대학교', 'Hanyang Cyber University', 'MAIN', 'hycu.ac.kr'),
    ('한일장신대학교', 'Haniluniv.&Presb.Theol.Sem.', 'MAIN', 'hanil.ac.kr'),
    ('한중대학교', 'Hanzhong University', 'MAIN', 'HANZHONG.ac.kr'),
    ('협성대학교', 'Hyupsunguniversity', 'MAIN', 'uhs.ac.kr'),
    ('호남대학교', 'Honam University', 'MAIN', 'honam.ac.kr'),
    ('호남신학대학교', 'Honam Theological University & Seminary', 'MAIN', 'htus.ac.kr'),
    ('호서대학교', 'Hoseo University', 'MAIN', 'hoseo.ac.kr'),
    ('호원대학교', 'Howon University', 'MAIN', 'howon.ac.kr'),
    ('홍익대학교', 'Hongik University', 'MAIN', 'hongik.ac.kr'),
    ('홍익대학교', 'Hongik University', 'SECOND', 'hongik.ac.kr'),
    ('화성의과학대학교', 'HWASUNG MEDI-SCIENCE UNIVERSITY', 'MAIN', 'hsmu.ac.kr'),
    ('화신사이버대학교', 'Hwashin Cyber University', 'MAIN', 'hscu.ac.kr'),
    ('ICT폴리텍대학', 'ICT Polytech Institute of Korea', 'MAIN', 'ict.ac.kr'),
    ('가톨릭상지대학교', 'Catholic Sangji College', 'MAIN', 'csj.ac.kr'),
    ('강동대학교', 'Gangdong University', 'MAIN', 'gangdong.ac.kr'),
    ('강릉영동대학교', 'Gangneung Yeongdong University', 'MAIN', 'gyu.ac.kr'),
    ('강원관광대학교', 'Kangwon Tourism College', 'MAIN', 'kt.ac.kr'),
    ('강원도립대학교', 'Gangwon State University', 'MAIN', 'gw.ac.kr'),
    ('거제대학교', 'Geoje University', 'MAIN', 'koje.ac.kr'),
    ('경기과학기술대학교', 'Gyeonggi University Of Science And Technology', 'MAIN', 'gtec.ac.kr'),
    ('가야대학교(고령)', 'Kaya University', 'SECOND', 'WWW.KAYA.AC.KR'),
    ('가야대학교(김해)', 'Kaya University', 'MAIN', 'WWW.KAYA.AC.KR'),
    ('가천대학교', 'Gachon University', 'MAIN', 'gachon.ac.kr'),
    ('가톨릭관동대학교', 'Catholic Kwandong University', 'MAIN', 'cku.ac.kr'),
    ('가톨릭꽃동네대학교', 'Catholic Kkottongnae University', 'MAIN', 'kkot.ac.kr'),
    ('가톨릭대학교', 'The Catholic University Of Korea', 'MAIN', 'catholic.ac.kr'),
    ('가톨릭대학교', 'The Catholic University Of Korea', 'SECOND', 'catholic.ac.kr'),
    ('가톨릭대학교', 'The Catholic University Of Korea', 'THIRD', 'catholic.ac.kr'),
    ('감리교신학대학교', 'Methodist Theological University', 'MAIN', 'mtu.ac.kr'),
    ('강남대학교', 'Kangnam University', 'MAIN', 'kangnam.ac.kr'),
    ('강서대학교', 'GANGSEO UNIVERSITY', 'MAIN', 'gangseo.ac.kr'),
    ('강원대학교', 'Kangwon National University', 'MAIN', 'kangwon.ac.kr'),
    ('강원대학교', 'Kangwon National University', 'SECOND', 'kangwon.ac.kr'),
    ('건국대학교', 'Konkuk University', 'MAIN', 'konkuk.ac.kr'),
    ('건국대학교(글로컬)', 'Konkuk University', 'BRANCH', 'kku.ac.kr'),
    ('건양대학교', 'Konyang University', 'MAIN', 'konyang.ac.kr'),
    ('건양대학교', 'Konyang University', 'SECOND', 'konyang.ac.kr'),
    ('건양사이버대학교', 'Konyang Cyber University', 'MAIN', 'kycu.ac.kr'),
    ('경기대학교', 'Kyonggi University', 'MAIN', 'kyonggi.ac.kr'),
    ('경기대학교', 'Kyonggi University', 'SECOND', 'kyonggi.ac.kr'),
    ('경남과학기술대학교', 'Gyeongnam National University Of Science And Technology', 'MAIN', 'gntech.ac.kr'),
    ('경남대학교', 'Kyungnam University', 'MAIN', 'kyungnam.ac.kr'),
    ('경동대학교', 'Kyungdong University', 'MAIN', 'kduniv.ac.kr'),
    ('경동대학교', 'Kyungdong University', 'SECOND', 'kduniv.ac.kr'),
    ('경동대학교', 'Kyungdong University', 'THIRD', 'kduniv.ac.kr'),
    ('경동대학교', 'Kyungdong University', 'FOURTH', 'kduniv.ac.kr'),
    ('경북대학교', 'Kyungpook National University', 'MAIN', 'knu.ac.kr'),
    ('경상국립대학교', 'Gyeongsang National University', 'MAIN', 'gnu.ac.kr'),
    ('경성대학교', 'Kyungsung University', 'MAIN', 'ks.ac.kr'),
    ('경운대학교', 'Kyungwoon University', 'MAIN', 'ikw.ac.kr'),
    ('경운대학교(산업대)', 'Kyungwoon University', 'MAIN', 'ikw.ac.kr'),
    ('경인교육대학교', 'Gyeongin National University Of Education', 'MAIN', 'ginue.ac.kr'),
    ('경인교육대학교', 'Gyeongin National University Of Education', 'SECOND', 'ginue.ac.kr'),
    ('경일대학교', 'Kyungil University', 'MAIN', 'kiu.ac.kr'),
    ('경희대학교', 'Kyung Hee University', 'MAIN', 'khu.ac.kr'),
    ('경희사이버대학교', 'Kyung Hee Cyber University', 'MAIN', 'khcu.ac.kr'),
    ('계명대학교', 'Keimyung University', 'MAIN', 'kmu.ac.kr'),
    ('고려대학교', 'Korea University', 'MAIN', 'korea.ac.kr'),
    ('고려대학교(세종)', 'Korea University Sejong Campus', 'BRANCH', 'sejong.korea.ac.kr'),
    ('고려사이버대학교', 'The Cyber University Of Korea', 'MAIN', 'cuk.edu'),
    ('고신대학교', 'Kosin University', 'MAIN', 'kosin.ac.kr'),
    ('공주교육대학교', 'Gongju National University Of Education', 'MAIN', 'gjue.ac.kr'),
    ('광신대학교', 'Kwangshin University', 'MAIN', 'kwangshin.ac.kr'),
    ('광운대학교', 'Kwangwoon University', 'MAIN', 'kw.ac.kr'),
    ('광주가톨릭대학교', 'Gwangju Catholic University', 'MAIN', 'gjc.ac.kr'),
    ('광주과학기술원', 'Gwangju Institute Of Science And Technology', 'MAIN', 'gist.ac.kr'),
    ('광주교육대학교', 'Gwangju National University Of Education', 'MAIN', 'gnue.ac.kr'),
    ('광주대학교', 'Gwangju University', 'MAIN', 'gwangju.ac.kr'),
    ('광주여자대학교', 'Kwangju Women’S University', 'MAIN', 'kwu.ac.kr'),
    ('국립강릉원주대학교', 'Gangneung Wonju National University', 'MAIN', 'gwnu.ac.kr'),
    ('국립강릉원주대학교', 'Gangneung Wonju National University', 'SECOND', 'gwnu.ac.kr'),
    ('국립경국대학교', 'Gyeongguk National University', 'MAIN', 'andong.ac.kr'),
    ('국립공주대학교', 'Kongju National University', 'MAIN', 'kongju.ac.kr'),
    ('국립군산대학교', 'Kunsan National University', 'MAIN', 'kunsan.ac.kr');

-- 유저
INSERT INTO users (email, name, phone_number, student_number, provider)
VALUES
    ('user01@example.com', '홍길동', '010-1000-0001', '20250001', 'GOOGLE'),
    ('user02@example.com', '김철수', '010-1000-0002', '20250002', 'GOOGLE'),
    ('user03@example.com', '이영희', '010-1000-0003', '20250003', 'GOOGLE'),
    ('user04@example.com', '박민수', '010-1000-0004', '20250004', 'GOOGLE'),
    ('user05@example.com', '최서연', '010-1000-0005', '20250005', 'GOOGLE'),
    ('user06@example.com', '정우진', '010-1000-0006', '20250006', 'GOOGLE'),
    ('user07@example.com', '오하늘', '010-1000-0007', '20250007', 'GOOGLE'),
    ('user08@example.com', '윤예진', '010-1000-0008', '20250008', 'GOOGLE'),
    ('user09@example.com', '강도현', '010-1000-0009', '20250009', 'GOOGLE'),
    ('user10@example.com', '신가윤', '010-1000-0010', '20250010', 'GOOGLE'),
    ('user11@example.com', '서하준', '010-1000-0011', '20250011', 'GOOGLE'),
    ('user12@example.com', '문정우', '010-1000-0012', '20250012', 'GOOGLE'),
    ('user13@example.com', '김다은', '010-1000-0013', '20250013', 'GOOGLE'),
    ('user14@example.com', '이주원', '010-1000-0014', '20250014', 'GOOGLE'),
    ('user15@example.com', '박소현', '010-1000-0015', '20250015', 'GOOGLE'),
    ('user16@example.com', '양도균', '010-1000-0016', '20250016', 'GOOGLE'),
    ('user17@example.com', '조하림', '010-1000-0017', '20250017', 'GOOGLE'),
    ('user18@example.com', '한예준', '010-1000-0018', '20250018', 'GOOGLE'),
    ('user19@example.com', '권민재', '010-1000-0019', '20250019', 'GOOGLE'),
    ('user20@example.com', '임소연', '010-1000-0020', '20250020', 'GOOGLE');

-- 동아리
INSERT INTO club (club_category, university_id, name, description, introduce, image_url, location)
VALUES ('ACADEMIC', 1, 'BCSD', '즐겁게 일하고 열심히 노는 IT 특성화 동아리! 코인 만든 동아리예요~',
        'BCSD는 IT 실무 프로젝트를 경험하며 성장하는 동아리입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png',
        '학생회관 101호'),
       ('SPORTS', 1, 'CUT', '한기대 탁구동아리🏓',
        'CUT은 탁구를 즐기며 친목을 다지는 동아리입니다.',
        'https://static.koreatech.in/upload/LOST_ITEMS/2025/6/12/bbacbbb4-5f64-4582-8f5f-e6e446031362/1000035027.jpg',
        '학생회관 102호'),
       ('PERFORMANCE', 1, 'K-오케스트라', '아름다운 음악과 재미있는 합주!',
        'K-오케스트라는 음악적 재능을 함께 나누고 성장하는 동아리입니다.',
        'https://static.koreatech.in/upload/LOST_ITEMS/2025/6/15/e12716ab-d5bc-4143-9101-5a2b6f0bfb94/1000014263.jpg',
        '학생회관 103호'),
       ('SPORTS', 1, '스텝업', '클라이밍 붐은 온다. 🧗',
        '스텝업은 클라이밍을 배우고 체력을 기르는 동아리입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/7/7/a72b37fb-e82b-4cbb-a2c2-4c59d8fc6b84/923ECFF9-871B-40A3-A13A-8230F0B666F8.jpeg',
        '학생회관 104호'),
       ('ACADEMIC', 1, 'K-ROAD', 'K-ROAD는 자율주행 연구와 대회 참가로 성과를 내는연구 단체입니다.',
        'K-ROAD는 자율주행 연구와 대회 참가를 통해 실력을 쌓는 동아리입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/7/8/7b60e632-0d24-4200-9891-a6dc15a72330/IMG_6794.png',
        '학생회관 105호'),
       ('SPORTS', 1, 'S.A.M', '안녕하세요! 스쿼시 동아리 S.A.M 입니다!',
        'S.A.M은 스쿼시를 즐기며 체력과 친목을 다지는 동아리입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/7/17/446479f5-c109-48c5-bd63-f38942ef356d/sam 로고 반전.jpg',
        '학생회관 106호'),
       ('SPORTS', 1, 'SMASH', '한국기술교육대학교 테니스 동아리',
        'SMASH는 테니스를 배우고 실력을 향상시키는 동아리입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/7/30/611ddcef-faa9-4302-8112-092ea3a48e67/1000031983.jpg',
        '학생회관 107호'),
       ('RELIGION', 1, 'SED-TUA', '한기대 가톨릭/천주교 동아리',
        'SED-TUA는 종교 활동과 봉사로 함께 성장하는 동아리입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/8/6/34c9902e-fbc7-4e5e-96f2-8e53bfe601b4/1000003833.jpg',
        '학생회관 108호'),
       ('PERFORMANCE', 1, '비상', '낭만과 행복이 가득한 어쿠스틱 기타 공연 동아리',
        '비상은 기타 공연과 음악 활동을 즐기는 동아리입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/8/8/84a933e3-4473-45e3-9057-cc573acdb982/1000034369.png',
        '학생회관 109호'),
       ('HOBBY', 1, '셔터', '안녕하세요! 한국기술대학교 사진 동아리 ''셔터''입니다!',
        '셔터는 사진 촬영과 편집을 즐기는 학생들의 모임입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/8/16/429d1be5-da62-4f53-b033-f6e01a55feeb/5763.png',
        '학생회관 110호'),
       ('PERFORMANCE', 1, '극예술연구회', '행동하는 젊음! 연극을 만들고 낭만을 새기는 동아리, 극예술연구회입니다.',
        '극예술연구회는 연극과 공연을 제작하며 창의력을 키우는 동아리입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/9/3/f3821e52-c695-4482-8114-862e8bde4527/9498.png',
        '학생회관 111호'),
       ('PERFORMANCE', 1, '한소리', '한기대 유일무이 풍물패 입니다!',
        '한소리는 풍물 연주와 전통 문화 체험을 함께 즐기는 동아리입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/10/13/c23361f0-f7ff-4eee-ae9c-7577d5bab4da/1000006554.jpg',
        '학생회관 112호');

-- 태그
INSERT INTO club_tag (name)
VALUES ('IT'),
       ('프로그래밍'),
       ('스터디'),
       ('프로젝트'),
       ('탁구'),
       ('운동'),
       ('음악'),
       ('합주'),
       ('공연'),
       ('클라이밍'),
       ('자율주행'),
       ('연구'),
       ('대회'),
       ('스쿼시'),
       ('테니스'),
       ('가톨릭'),
       ('종교'),
       ('봉사'),
       ('기타'),
       ('사진'),
       ('촬영'),
       ('연극'),
       ('예술'),
       ('풍물'),
       ('전통');

-- 동아리 태그 매핑
INSERT INTO club_tag_map (club_id, tag_id)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (2, 5),
       (2, 6),
       (3, 7),
       (3, 8),
       (3, 9),
       (4, 10),
       (4, 6),
       (5, 11),
       (5, 12),
       (5, 13),
       (6, 14),
       (6, 6),
       (7, 15),
       (7, 6),
       (8, 16),
       (8, 17),
       (9, 7),
       (9, 9),
       (9, 19),
       (10, 20),
       (10, 21),
       (11, 22),
       (11, 23),
       (12, 24),
       (12, 25);

-- 동아리 직책
INSERT INTO club_position (club_id, name, club_position_group)
VALUES (1, '회장', 'PRESIDENT'),
       (1, '부회장', 'PRESIDENT'),
       (1, '총무', 'MANAGER'),
       (1, '일반 회원', 'MEMBER'),
       (2, '회장', 'PRESIDENT'),
       (2, '부회장', 'PRESIDENT'),
       (2, '총무', 'MANAGER'),
       (2, '일반 회원', 'MEMBER'),
       (3, '회장', 'PRESIDENT'),
       (3, '부회장', 'PRESIDENT'),
       (3, '총무', 'MANAGER'),
       (3, '일반 회원', 'MEMBER'),
       (4, '회장', 'PRESIDENT'),
       (4, '부회장', 'PRESIDENT'),
       (4, '총무', 'MANAGER'),
       (4, '일반 회원', 'MEMBER'),
       (5, '회장', 'PRESIDENT'),
       (5, '부회장', 'PRESIDENT'),
       (5, '총무', 'MANAGER'),
       (5, '일반 회원', 'MEMBER'),
       (6, '회장', 'PRESIDENT'),
       (6, '부회장', 'PRESIDENT'),
       (6, '총무', 'MANAGER'),
       (6, '일반 회원', 'MEMBER'),
       (7, '회장', 'PRESIDENT'),
       (7, '부회장', 'PRESIDENT'),
       (7, '총무', 'MANAGER'),
       (7, '일반 회원', 'MEMBER'),
       (8, '회장', 'PRESIDENT'),
       (8, '부회장', 'PRESIDENT'),
       (8, '총무', 'MANAGER'),
       (8, '일반 회원', 'MEMBER'),
       (9, '회장', 'PRESIDENT'),
       (9, '부회장', 'PRESIDENT'),
       (9, '총무', 'MANAGER'),
       (9, '일반 회원', 'MEMBER'),
       (10, '회장', 'PRESIDENT'),
       (10, '부회장', 'PRESIDENT'),
       (10, '총무', 'MANAGER'),
       (10, '일반 회원', 'MEMBER'),
       (11, '회장', 'PRESIDENT'),
       (11, '부회장', 'PRESIDENT'),
       (11, '총무', 'MANAGER'),
       (11, '일반 회원', 'MEMBER'),
       (12, '회장', 'PRESIDENT'),
       (12, '부회장', 'PRESIDENT'),
       (12, '총무', 'MANAGER'),
       (12, '일반 회원', 'MEMBER');

-- 동아리 멤버
INSERT INTO club_member (club_id, user_id, club_position_id)
VALUES (1, 1, 1),
       (1, 2, 2),
       (1, 3, 3),
       (1, 5, 4),
       (1, 7, 4),
       (2, 2, 5),
       (2, 4, 6),
       (2, 6, 8),
       (2, 8, 8),
       (2, 10, 8),
       (2, 1, 8),
       (3, 1, 9),
       (3, 2, 12),
       (3, 9, 12),
       (4, 4, 13),
       (4, 6, 16),
       (4, 12, 16),
       (5, 3, 17),
       (5, 7, 18),
       (5, 1, 19),
       (5, 11, 20),
       (5, 15, 20),
       (6, 5, 21),
       (6, 8, 24),
       (6, 1, 24),
       (7, 9, 25),
       (7, 10, 28),
       (7, 16, 28),
       (8, 11, 29),
       (8, 12, 32),
       (8, 17, 32),
       (9, 14, 33),
       (9, 18, 36),
       (10, 6, 37),
       (10, 15, 40),
       (10, 19, 40),
       (11, 8, 41),
       (11, 13, 44),
       (11, 20, 44),
       (12, 2, 45),
       (12, 5, 46),
       (12, 9, 48),
       (12, 14, 48);

INSERT INTO club_recruitment (club_id, start_date, end_date)
VALUES (1, '2025-11-30', '2025-12-31'),
       (2, '2025-11-29', '2025-12-31'),
       (3, '2025-11-28', '2025-12-31'),
       (4, '2025-11-27', '2025-12-31');

INSERT INTO council (name, image_url, university_id, introduce, personal_color, location, phone_number, email, instagram_url, operating_hour)
VALUES ('개화', 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png', 1,
        '총동아리연합회는 한국기술교육대학교 내 모든 동아리의 활동을 지원하고 관리하는 학생 자치 기구입니다.\n\n동아리 간의 원활한 소통을 증진하고, 동아리 문화 발전을 위해 다양한 행사와 지원 프로그램을 운영하고 있습니다.\n\n동아리 운영에 필요한 각종 행정 지원, 예산 지원, 시설 관리 등을 담당하며, 동아리 박람회, 축제 등 대형 행사를 주관합니다.',
        '#C9DEF3', '학생회관 2층 202호', '041-560-1234', 'council@koreatech.ac.kr', 'https://www.instagram.com/koreatech_council', '평일 09:00 ~ 18:00');

INSERT INTO council_notice (council_id, title, content)
VALUES (1, '2025학년도 2학기 동아리 지원금 신청 안내',
        '안녕하세요, 총동아리연합회입니다.\n\n2025학년도 2학기 동아리 지원금 신청을 다음과 같이 안내드립니다.\n\n■ 신청 기간\n- 2025년 12월 10일(화) ~ 12월 20일(금) 18:00까지\n\n■ 지원 대상\n- 정동아리 및 준동아리로 등록된 모든 동아리\n- 2학기 활동 계획서를 제출한 동아리\n\n■ 지원 금액\n- 정동아리: 최대 500,000원\n- 준동아리: 최대 300,000원\n\n■ 신청 방법\n1. 총동아리연합회 홈페이지 접속\n2. 지원금 신청서 다운로드\n3. 활동 계획서 및 예산 계획서 작성\n4. 이메일(council@koreatech.ac.kr)로 제출\n\n■ 제출 서류\n- 동아리 지원금 신청서\n- 2학기 활동 계획서\n- 예산 사용 계획서\n- 동아리 등록증 사본\n\n■ 심사 기준\n- 활동 계획의 구체성 및 실현 가능성\n- 예산 계획의 적정성\n- 지난 학기 활동 실적\n\n■ 결과 발표\n- 2025년 12월 27일(금) 개별 공지\n\n기타 문의사항은 총동아리연합회실(학생회관 2층 202호) 또는 이메일로 연락 주시기 바랍니다.\n\n감사합니다.'),
       (1, '동아리 박람회 참가 신청 마감 안내',
        '안녕하세요, 총동아리연합회입니다.\n\n2026학년도 신입생 환영 동아리 박람회 참가 신청 마감을 안내드립니다.\n\n■ 행사 개요\n- 행사명: 2026 신입생 환영 동아리 박람회\n- 일시: 2026년 3월 5일(수) ~ 3월 6일(목) 10:00~17:00\n- 장소: 대학본부 앞 광장\n\n■ 참가 신청 마감\n- 마감일: 2025년 12월 15일(일) 23:59\n- 신청 방법: 구글 폼을 통한 온라인 신청\n- 신청 링크: https://forms.gle/example\n\n■ 부스 배정\n- 1차 추첨: 2025년 12월 18일(수)\n- 부스 위치 공지: 2025년 12월 20일(금)\n\n■ 참가 동아리 혜택\n- 동아리 홍보 부스 제공 (2m x 2m)\n- 홍보 현수막 게시 지원\n- 박람회 홍보 포스터에 동아리명 게재\n\n■ 준비 사항\n- 동아리 소개 자료 (포스터, 리플렛 등)\n- 체험 프로그램 (선택사항)\n- 신입 부원 모집 양식\n\n■ 주의 사항\n- 마감일 이후 신청 불가\n- 부스 배정 후 참가 취소 시 다음 학기 행사 참가 제한\n- 안전 관리 및 뒷정리는 각 동아리 책임\n\n많은 동아리의 참여 부탁드립니다.\n\n문의: 총동아리연합회 (041-560-1234)'),
       (1, '총동아리연합회(개화) 신입 국원 추가 모집 안내',
        '안녕하세요, 총동아리연합회 개화입니다.\n\n2025학년도 2학기 총동아리연합회 신입 국원을 추가 모집합니다.\n\n■ 모집 부서 및 인원\n- 기획부: 2명\n- 홍보부: 2명\n- 복지부: 1명\n- 총무부: 1명\n\n■ 지원 자격\n- 한국기술교육대학교 재학생 (휴학생 지원 가능)\n- 동아리 활동 경험자 우대\n- 학년 및 전공 무관\n\n■ 활동 내용\n- 동아리 지원 사업 기획 및 운영\n- 동아리 행사 준비 및 진행\n- 동아리 간 소통 및 협력 지원\n- 동아리 예산 관리 및 집행\n\n■ 활동 혜택\n- 총동아리연합회 활동 인증\n- 각종 행사 기획 및 운영 경험\n- 동아리 네트워크 형성\n- 총동아리연합회 MT 및 워크샵 참가\n\n■ 지원 기간\n- 2025년 12월 3일(화) ~ 12월 13일(금) 18:00\n\n■ 지원 방법\n1. 지원서 다운로드 (총동아리연합회 인스타그램 또는 이메일 요청)\n2. 지원서 작성 후 이메일 제출\n3. 서류 합격자 개별 연락 (12월 16일)\n4. 면접 진행 (12월 18일~19일)\n\n■ 선발 일정\n- 서류 접수: ~12월 13일(금)\n- 서류 합격자 발표: 12월 16일(월)\n- 면접: 12월 18일(수)~19일(목)\n- 최종 합격자 발표: 12월 20일(금)\n\n■ 제출 서류\n- 지원서 1부\n- 자기소개서 1부\n- 포트폴리오 (선택사항)\n\n동아리 문화 발전에 함께할 열정적인 분들의 많은 지원 바랍니다!\n\n문의: council@koreatech.ac.kr\n인스타그램: @koreatech_council'),
       (1, '동아리방 이용 수칙 안내',
        '안녕하세요, 총동아리연합회입니다.\n\n쾌적한 동아리방 환경 조성을 위한 이용 수칙을 안내드립니다.\n\n■ 기본 이용 수칙\n- 동아리방은 해당 동아리 부원만 이용 가능합니다\n- 이용 시간: 평일 09:00~22:00, 주말 10:00~20:00\n- 시설물 파손 시 변상 의무가 있습니다\n\n■ 청결 수칙\n- 음식물은 지정된 장소에서만 섭취 가능\n- 쓰레기는 분리수거하여 배출\n- 퇴실 시 청소 및 정리정돈 필수\n- 주 1회 대청소 실시 (각 동아리 자율)\n\n■ 안전 수칙\n- 화기 사용 금지\n- 전열기구 사용 시 안전 수칙 준수\n- 퇴실 시 전원 차단 및 시건 확인\n- 귀중품은 개인이 직접 관리\n\n■ 점검 사항\n- 매월 1회 총동아리연합회 순회 점검\n- 수칙 위반 시 경고 및 동아리방 사용 제한\n- 3회 경고 시 한 학기 사용 정지\n\n■ 시설 이용 신청\n- 프로젝터, 음향기기 등은 사전 예약 필수\n- 예약 방법: 구글 폼 또는 방문 신청\n\n여러분의 협조로 모두가 쾌적하게 이용할 수 있는 동아리방이 되기를 바랍니다.\n\n감사합니다.'),
       (1, '2025 겨울방학 동아리 시설 점검 및 보수 안내',
        '안녕하세요, 총동아리연합회입니다.\n\n2025년 겨울방학 기간 동안 동아리 시설 점검 및 보수 작업이 진행될 예정입니다.\n\n■ 점검 기간\n- 2026년 1월 6일(월) ~ 1월 24일(금)\n\n■ 점검 대상\n- 동아리방 (학생회관 3층~5층)\n- 동아리 연습실\n- 동아리 창고\n- 공용 시설 (복도, 화장실 등)\n\n■ 점검 내용\n- 전기/전등 시설 점검 및 교체\n- 냉난방 시설 점검\n- 책상, 의자 등 집기 파손 여부 확인\n- 도배, 장판 보수\n- 방역 작업\n\n■ 동아리별 협조 사항\n1. 1월 3일(금)까지 동아리방 정리 및 청소\n2. 귀중품 및 개인 물품 별도 보관\n3. 수리가 필요한 사항 사전 제출\n4. 점검 기간 중 동아리방 출입 제한\n\n■ 보수 신청\n- 신청 기간: ~12월 20일(금)\n- 신청 방법: 이메일로 보수 신청서 제출\n- 보수 범위: 기본 시설물에 한함\n- 동아리 귀책 사유 파손은 유상 수리\n\n■ 재입실 일정\n- 2026년 1월 27일(월)부터 입실 가능\n- 입실 전 청소 상태 확인 및 인수인계\n\n점검 기간 중 불편을 드려 죄송하며, 더 나은 환경을 위한 양해 부탁드립니다.\n\n문의: 총동아리연합회 (041-560-1234, council@koreatech.ac.kr)');
