name: Flyway Version Validator

on: [pull_request]

jobs:
  check-flyway-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Fetch all branches
      run: git fetch --all

    - name: Run Flyway version check
      run: python .github/SCRIPT/check_flyway_version.py
